apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-eks-app
  template:
    metadata:
      labels:
        app: python-eks-app
    spec:
     - containers:
        - name: python-eks-app
          image: imran12345/app.py:1.0
          ports:
        - containerPort: 5000
