###cicd workflow for python application to github actions 

name: CI/CD to AWS EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: ${{ vars.DOCKER_REPO }}
      DOCKER_URI: ${{ vars.DOCKER_URI }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      CLUSTER_NAME: <your-eks-cluster>

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/app.py:1.0 .

      - name: Push Docker image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/app.py:1.0

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
